name: Test Action

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'action.yml', 'main.rb' ]
  pull_request:
    branches: [ main ]
    paths: [ 'action.yml', 'main.rb' ]

jobs:
  test-livecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test livecheck with dry-run
        uses: ./ # Use this action from the current repo
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          cask: slack
          tag: v1.0.0
          dryrun: true
  test-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test bump with dry-run
        uses: ./ # Use this action from the current repo
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          cask: slack
          tag: v1.0.0
          dryrun: true
